name: Lint
on:
  push:
    paths:
      - src/**
      - .github/workflows/lint.yml

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install

      - run: npm run lint

      - uses: EndBug/add-and-commit@v4
        with:
          message: '[auto] chore: lint source code'
          add: src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
