name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: npm install

      - run: npm test
        env:
          TEST_CREDS: ${{ secrets.TEST_CREDS }}
